//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group9_Project_CT050_3_2_WAPP {
    
    
    public partial class Admin {
        
        // Note: In a real implementation, you would have control declarations here
        // for any server controls that need to be accessed from code-behind.
        // Since our current implementation uses mostly client-side controls,
        // we don't have many server controls to declare.
        
        // Example of how control declarations would look:
        // 
        // /// <summary>
        // /// TeamCountLabel control.
        // /// </summary>
        // /// <remarks>
        // /// Auto-generated field.
        // /// To modify move field declaration from designer file to code-behind file.
        // /// </remarks>
        // protected global::System.Web.UI.WebControls.Label TeamCountLabel;
    }
} 